### ISSUE TITLE
 { "action": "reloadBackend", "role": "admin"} shows login mask

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#184]
```
          {
            "action": "reloadBackend",
            "role": "advanced-editor"
          },
          {
            "action": "see",
            "text": "Page"
          },
          {
            "action": "click",
            "link": "Page"
          },
          {
            "action": "makeScreenshotOfWindow",
            "fileName": "AdvancedEditorUser",
            "captionText": "The backend view for the \"advanced\\_editor\""
          },
        
```

 ![TYPO3 CMS Screenshots Runner Codeception Introduction IntroductionCest makeScreenshots fail](https://user-images.githubusercontent.com/48202465/125942907-988a0666-2e77-4825-b75b-d6c13a747a61.png)

Here is the complete action: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/blob/012afe2921ea3231297ba88900242d6970f877c9/screenshots.json#L906

**Comment by alexander-nitsche** [comment]
Yes, this is due to the switching users further up in the `screenshots.json`: The `reloadBackend` is based on session hashes of logged in users. With the switching of users in the backend these hashes change and `reloadBackend` does not work anymore. This problem can be currently worked around by moving the switching user screenshots to the end of the `screenshots.json` and insert new action blocks before.

**Comment by alexander-nitsche** [comment]
You could leave a note with comments in the screenshots.json that this block has always to be the last.

**Comment by linawolf** [comment]
Ok let's use this as work-around. What happens though if we are running all screenshots at once, not limited to one tutorial?

**Comment by alexander-nitsche** [comment]
Is not a problem, as each suite gets run in its own TYPO3 instance. It is only a problem in the same suite of the same `screenshots.json`.
